
nameOverride: ""
fullnameOverride: ""

exporter:
  image: michaelbui99/salling-foodwaste-prometheus-exporter
  tag: latest
  containerPort: 8080

  labels: {}
  podAnnotations: {}

  replicas: 1

  imagePullSecrets: []

  # Used to set the FW_EXPORTER_API_KEY environment variable
  apiKeySecretRef:
    # Name of the secret containing the API key
    name: 
    # Key in the secret that contains the API key
    key: 

  service:
    enable: true
    servicePort: 80

  ingress:
    enable: false

