nameOverride: ""
fullnameOverride: ""
namespaceOverride: ""

exporter:
  image: michaelbui99/salling-foodwaste-prometheus-exporter
  tag: latest
  containerPort: 8080

  labels: {}
  podAnnotations: {}

  replicas: 1

  imagePullSecrets: []

  # Used to set the FW_EXPORTER_API_KEY environment variable
  apiKeySecretRef:
    # Name of the secret containing the API key
    name:  
    # Key in the secret that contains the API key
    key: 

  zipCodes: []

  service:
    enable: true

  ingress:
    enable: false

serviceMonitor:
  serviceMonitorSelector: "prometheus"
  enable: true
  namespaceSelector:
    matchNames: []
  scrapeInterval: 2h
    