{{- if or (not $.Values.exporter.apiKeySecretRef) (or (not $.Values.exporter.apiKeySecretRef.key) (not $.Values.exporter.apiKeySecretRef.name)) }}
 {{ fail "apiKeySecretRef must be set" }}
{{- end }}

apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        {{- include "exporter.labels" $ | nindent 8 }}
    name: {{ include "exporter.fullname" $ }}
    namespace: {{ include "exporter.namespace" $ }}
spec:
    replicas: {{ $.Values.exporter.replicas }}
    selector:
        matchLabels:
            app: {{ include "exporter.fullname" $ }}
    template:
        metadata:
            labels: 
            {{- include "exporter.labels" $ | nindent 16 }}
            {{- if $.Values.exporter.podAnnotations }}
            annotations:
            {{- range $k, $v := .Values.exporter.podAnnotations}}
            {{- printf "%s: %s" $k ($v | quote) | nindent 16 }}
            {{- end }}
            {{- end }}
        spec:
            imagePullSecrets:
            {{- range $secret := $.Values.exporter.imagePullSecrets }}
                - name: {{ $secret }}
            {{- end }}
            containers:
                - image: {{ $.Values.exporter.image }}:{{ $.Values.exporter.tag }}
                  name: salling-foodwaste-prometheus-exporter
                  ports:
                    - containerPort: {{ $.Values.exporter.containerPort }}
                  env:
                    - name: "FW_EXPORTER_PORT"
                      value: {{ $.Values.exporter.containerPort  | quote}}
                      {{- $zipCodes := join ", " $.Values.exporter.zipCodes }}
                    - name: "FW_EXPORTER_ZIP_CODES"
                      value: '[ "{{ $zipCodes }}" ]'
                    - name: "FW_EXPORTER_API_KEY"
                      valueFrom:
                        secretKeyRef:
                          name: {{ $.Values.exporter.apiKeySecretRef.name }}
                          key: {{ $.Values.exporter.apiKeySecretRef.key }}
                  livenessProbe:
                    httpGet:
                        path: /healthy
                        port: {{ $.Values.exporter.containerPort }}
                    initialDelaySeconds: 5
                    periodSeconds: 10
                    timeoutSeconds: 1
                    successThreshold: 1
                    failureThreshold: 3
                  readinessProbe:
                    httpGet:
                        path: /healthy
                        port: {{ $.Values.exporter.containerPort }}
                    initialDelaySeconds: 5
                    periodSeconds: 10
                    timeoutSeconds: 1
                    successThreshold: 1
                    failureThreshold: 3
