{{- if $.Values.exporter.service.enable }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "exporter.fullname" $ }}
  labels:
    {{- include "exporter.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ include "exporter.fullname" $ | quote }}
  ports:
  - protocol: TCP
    port: {{ $.Values.exporter.service.servicePort }}
    targetPort: {{ .Values.exporter.containerPort | required "A container port is required." }}
{{- end }}