{{- if $.Values.serviceMonitor.enable }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    {{include "exporter.labels" $ | nindent 8}}
        release: {{ $.Values.serviceMonitor.serviceMonitorSelector }}
  name: {{ include "exporter.fullname" $ }}
  namespace: {{ include "exporter.namespace" $ }}
spec:
  endpoints:
  - interval: {{ $.Values.serviceMonitor.scrapeInterval }}
    targetPort: {{ $.Values.exporter.containerPort }}
    path: /metrics
  namespaceSelector:
    matchNames: {{ $.Values.serviceMonitor.namespaceSelector.matchNames }}
    
  selector:
    matchLabels:
      app: {{ include "exporter.fullname" $ }}
{{- end }}