on:
  push:
    branches:
      - "main"
    paths:
      - app/**
      - Dockerfile
      - .github/workflows/image.yaml

env:
  IMAGE_NAME: "salling-foodwaste-prometheus-exporter"
  IMAGE_TAG: ${{ github.sha }}
  CONTAINER_REPO: ${{ vars.DOCKERHUB_USERNAME }}

jobs:
  images:
    runs-on: ubuntu-22.04
    steps:
      - name: "Checkout repo"
        uses: "actions/checkout@v4"

      - name: "Setup docker"
        uses: "docker/setup-buildx-action@v3"

      - name: "Docker authentication"
        uses: "docker/login-action@v3"
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: "Build image - SHA"
        run: docker build -t "$CONTAINER_REPO"/"$IMAGE_NAME":"$IMAGE_TAG" .

      - name: "Build image - latest"
        run: docker build -t "$CONTAINER_REPO"/"$IMAGE_NAME":latest .
      
      - name: "Push image - SHA"
        run: docker push "$CONTAINER_REPO"/"$IMAGE_NAME":"$IMAGE_TAG"

      - name: "Push image - latest"
        run: docker push "$CONTAINER_REPO"/"$IMAGE_NAME":latest
